" ================ General Settings ====================
set nocompatible
set number
set relativenumber
set history=700                " Sets how many lines of history VIM has to remember
set backspace=indent,eol,start " Allow backspace in insert mode
set showmode                   " Show current mode down the bottom
if has('gui_running')
  syntax on
endif
set showcmd                    " Show what commands you’re typing
set laststatus=2               " Show status line
set modeline                   " Allow modelines
set ruler                      " Show current line and column position in file
set title                      " Show file title in terminal tab
set cmdheight=2                " Sets the Height of the Command Line
set wildmenu                   " Turn on the WiLd menu, auto complete for commands in command line
set noerrorbells               " No sounds on error
set novisualbell

let mapleader = ","
let g:mapleader = ","

" This sets my shell to be equal to the current shell in my iterm
set shell=$SHELL\ -l

"Auto chdir in Vim
autocmd BufEnter * silent! lcd %:p:h

" automatically rebalance windows on vim resize
autocmd VimResized * :wincmd =

" ========= Files, Backups, and Swap Files ==========
set noswapfile                  " Makes it so no .swp file is created when working on a project
set nowb
set nobackup
set autoread

" If Focus is lost on the terminal, autosave
au FocusGained,BufEnter * :silent! !
au FocusLost,WinLeave * :silent! w

" ================ Interactions ==============================

set scrolloff=3                 " Start scrolling slightly before the cursor reaches an edge
set sidescrolloff=5             " Scroll sideways a character at a time, rather than a screen at a time
set sidescroll=1
set mouse=a             " Enable mouse use in all modes
set clipboard=unnamed   " Allows yy to work with clipboard

" =============== Vundle Initialization ===============
" This loads all the plugins specified in ~/.vim/vundles.vim
if filereadable(expand("~/.vim/vundles.vim"))
  source ~/.vim/vundles.vim
endif

" ================ Custom Settings ========================
let g:rspec_runner = "os_x_iterm2"
" This loads all the settings specified in ~/.vim/settings.vim
if filereadable(expand("~/.vim/vundles.vim"))
  source ~/.vim/settings.vim
endif
