#!/bin/bash
#
source $HOME/.bashrc  # get aliases
source $HOME/.bash-aliases # get aliases
source $HOME/.git-prompt.sh
export PATH=/Applications/MAMP/bin/php/php5.6.2/bin:~/.composer/vendor/bin:$PATH
export MAMP_PHP=/Applications/MAMP/bin/php/php5.6.10/bin
export PATH="$MAMP_PHP:$PATH"
export PATH="$PATH:~/bin"
export TERM="xterm-256color"


export EDITOR="mvim"

# [[ $- != *i* ]] && return
# [[ -z "$TMUX" ]] && exec tmux


if [ -f `brew --prefix`/etc/bash_completion ]; then
    . `brew --prefix`/etc/bash_completion
  else
    echo "run: brew install git bash-completion"
fi

if [ -f /usr/local/share/chruby/chruby.sh ]; then
  source '/usr/local/share/chruby/chruby.sh'
  source '/usr/local/share/chruby/auto.sh'
  chruby ruby-2.2.5
else
  echo "Ain't got no chruby"
fi

function parse_ruby_version {
  ruby --version | cut -d' ' -f 1-2
}

export GIT_PS1_SHOWDIRTYSTATE=1 
export GIT_PS1_SHOWSTASHSTATE=1
export GIT_PS1_SHOWTRACKEDFILES=1


if test "$(uname)" = "Darwin"
  PS1="\[\033[32m\][\w]\[\033[0m\] \033[35m\][ \$(/bin/ls -1 | /usr/bin/wc -l | gsed 's: ::g') files ]\n\[\033[1;36m\]\u\[\033[1;31m\] [$(chruby_preexec_bash_set)$(parse_ruby_version)]:$(tput sgr0)\$(__git_ps1) \e[34m\] ☁︎ \[\e[0m\] "
then
elif test "$(expr substr $(uname -s) 1 5)" = "Linux"
  PS1="\[\033[32m\][\w]\[\033[0m\] \033[35m\][ \$(/bin/ls -1 | /usr/bin/wc -l | sed 's: ::g') files ]\n\[\033[1;36m\]\u\[\033[1;31m\] [$(chruby_preexec_bash_set)$(parse_ruby_version)]:$(tput sgr0)\$(__git_ps1) \e[34m\] ☁︎ \[\e[0m\] "
then
fi

export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad
